### ISSUE TITLE
Error Accessing the facade

### ISSUE THREAD

**Issue by webface** [alexpechkarev/google-geocoder#10]
use Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvider;

$param = array("address"=>$request->input('address').' '.$request->input('city').' '.$request->input('state'));
        $response = \Geocoder::geocode('json', $param);
        return $response;

I get the error..

FatalErrorException in ProfileController.php line 49:
Class 'Geocoder' not found

How do I reference this class? Thanks

**Comment by alexpechkarev** [comment]
Hi webface,

Change: use Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvider;
to
use Alexpechkarev\GoogleGeocoder\GoogleGeocoder.php

Regards,
Alexander

**Comment by telcy** [comment]
I have the same problem and your suggestion does not fix it.

Laravel 5.1

Any other things we can do? thanks

**Comment by alexpechkarev** [comment]
Hi telcy,

Please can you provide example of your code ?
Regards

**Comment by telcy** [comment]
Just tried it again today. And it is working. Never mind..

Thanks :)

**Comment by alexpechkarev** [comment]
Great to hear that telcy!
