### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by xabou** [alexpechkarev/google-geocoder#11]
You should replace deprecated share method with singleton in GoogleGeocoderServiceProvider.

`
$this->app['GoogleGeocoder'] = $this->app->share(function($app)
`

to

`
  $this->app->singleton('GoogleGeocoder', function($app)
`

**Comment by alexpechkarev** [comment]
Hi @xabou ,

Thank you for pointing out, the change has been applied.

Regards,
Alexander
