### ISSUE TITLE
Where to put the source files in laravel project directory?

### ISSUE THREAD

**Issue by akhilkrishnans** [alexpechkarev/google-geocoder#3]
Please describe where to put the source files in the laravel project directory.

Here is the error.

FatalErrorException in D:\Documents\Localhost\htdocs\finderkerala-fw\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php line 150:
Class 'Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvider' not found

**Comment by alexpechkarev** [comment]
HI akhilkrishnans,

Please register service provider in config/app.php and try again:

'providers' => [
....
'Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvide',

Regards,
Alexander

**Comment by akhilkrishnans** [comment]
Its already done. Still I had a recheck on it.
But the error persists.

On Tue, Mar 3, 2015 at 7:10 PM, Alexander Pechkarev <
notifications@github.com> wrote:

> HI akhilkrishnans,
> 
> Please register service provider in config/app.php and try again:
> 
> 'providers' => [
> ....
> 'Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvide',
> 
> Regards,
> Alexander
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexpechkarev/google-geocoder/issues/3#issuecomment-76946498
> .

## 

Thanks and Regards,

_Akhil Krishnan_
_Chief Executive Officer_

_Nubeslogic Software Solutions (P) Ltd._

*CIN *: U72200KL2014PTC037472

TC 14/1608, FO Lane, A-15A, Vazhuthacaud
Thiruvananthapuram – 14
Kerala, India

_Web_   : www.nubeslogic.com
*Email *: akhil@nubeslogic.com
*Skype *: akhilkrishnans
*Mob   *: +91 80 86 849 489

**Comment by alexpechkarev** [comment]
HI akhilkrishnans,
Please can you show me how and where you calling the Geocoder that throws error ? Also can you paste config/app.php ?

After registering service provider you should be  able to call geocoder from your controller.

Try 
php artisan clear-compiled
composer dump-autoload

Regards,
Alexander
