### ISSUE TITLE
Hard dependency for cURL not listed in composer.json

### ISSUE THREAD

**Issue by PerfectionIS** [alexpechkarev/google-geocoder#4]
This package requires PHP cURL to be installed in order for it to work, but it is not mentioned anywhere in the documentation or composer.json*. Also, there is a slight error in the documentation. The line:

$reponse = Geocoder::geocode('json', $param);

Should be:

$reponse = \Geocoder::geocode('json', $param);

*https://github.com/alexpechkarev/google-geocoder/blob/master/composer.json

**Comment by alexpechkarev** [comment]
Hi PerfectionIS.

Many thanks for pointing out, dependency and usage examples have been amended.
Regards,
Alexander
