### ISSUE TITLE
Can you provide options for not converting returned response to STRING

### ISSUE THREAD

**Issue by maximl337** [alexpechkarev/google-geocoder#8]

**Comment by alexpechkarev** [comment]
Hi maximl337,

You can specify required format in your call using first parameter, like this:
$response = \Geocoder::geocode('xml', $param);

Unfortunately, according Google Geocoding documentation output can only be in two forms JSON or XML.
https://developers.google.com/maps/documentation/geocoding/#GeocodingRequests

Regards,
Alexander

**Comment by VMRC91** [comment]
do you have any example project, where you implement it

**Comment by alexpechkarev** [comment]
Hi VMRC91,
By default returned response is string and is down to user to parse it accordingly into the output format, i.e. json_decode($response).  Have recently committed new package  Google Maps API for Laravel, please take a look there is an example controller, here is the URL:
https://github.com/alexpechkarev/google-maps/blob/master/src/Examples.php

Let me know if you have any questions.
Regards,
Alexander

**Comment by alexpechkarev** [comment]
Hi VMRC91,
Yes, the live example https://www.blackpoolpleasurebeach.com/wristbands/#/
On the completion of the online transaction purchaser address being geocoded to display location on the map ( for office use only ). This feature being used for marketing purposes.

Regards,
Alexander

**Comment by VMRC91** [comment]
Thank you so much…
I will tell you any thing about my project..

**Comment by VMRC91** [comment]
Excuse me Alexander

But wat i want i to show a location in a map, i have the coordinates and i want show it on a map, can you help me please.
with you dependence i can do this..???

how i can do this, do you have a example for it…??

Thank you 

Victor R

**Comment by alexpechkarev** [comment]
Hi Victor,

You will need to look at visualization of your data, which unfortunately is out of scope of this package.
To show location on the map once you have coordinates is fairly easily, take a look at Google Geo Chart https://developers.google.com/chart/interactive/docs/gallery/geochart

I have create an example on JSFiddle, showing location on the map along with name and value.
https://jsfiddle.net/20yd0ra5/

Regards,
Alexander
